version: "3"
services:
  db:
    image: mariadb:latest
    container_name: ryuou-manager-db
    ports:
      - "127.0.0.1:33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: ryuou_manager_db
